server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql
 returnPageInfo: check
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
spring:
 mvc:
  view:
   prefix: /
   suffix: .html